apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-02T08:37:06Z"
  labels:
    run: web-app
    hpecp.hpe.com/hpecp-internal-gateway: "true"
  name: web-app
  namespace: test-jenkins
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    name: "web"
    protocol: TCP
    targetPort: 80
  selector:
    run: web-app
  sessionAffinity: None
  type: NodePort
